---
title       : Communicating Results
subtitle    : Specifying Levels of Detail
author      : Roger D. Peng, Associate Professor of Biostatistics
job         : Johns Hopkins Bloomberg School of Public Health
logo        : bloomberg_shield.png
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
url:
  lib: ../../libraries
  assets: ../../assets
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## tl;dr

* People are busy, especially managers and leaders

* Results of data analyses are sometimes presented in oral form, but
  often the first cut is presented via email

* It is often useful to breakdown the results of an analysis into
  different levels of granularity / detail

* Getting responses from busy people: [http://goo.gl/sJDb9V](http://goo.gl/sJDb9V)

---

## Hierarchy of Information: Research Paper

* Title / Author list

* Abstract

* Body / Results

* Supplementary Materials / the gory details

* Code / Data / really gory details

---

## Hierarchy of Information: Email Presentation

* Subject line / Sender info

  - At a minimum; include one
  - Can you summarize findings in one sentence?

* Email body 

  - A brief description of the problem / context; recall what was
    proposed and executed; summarize findings / results; 1&ndash;2
    paragraphs

  - If action needs to be taken as a result of this presentation,
    suggest some options and make them as concrete as possible.

  - If questions need to be addressed, try to make them yes / no

---

## Hierarchy of Information: Email Presentation

* Attachment(s)

  - R Markdown file 
  - knitr report 

  - Stay concise; don't spit out pages of code (because you
    used knitr we know it's available)

* Links to Supplementary Materials

  - Code / Software / Data
  - GitHub repository / Project web site
  
