morris:
  css: css/morris.css
  jshead: 
    - js/jquery-1.8.2.min.js
    - js/raphael-2.1.0.min.js
    - js/morris.min.js
  cdn:
    css: "http://cdn.oesmith.co.uk/morris-0.4.2.min.css"
    jshead:
      - http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js
      - http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js
      - http://cdn.oesmith.co.uk/morris-0.4.2.min.js

