Regression models final project
===============================

## Context
You work for Motor Trend magazine. Looking at a data set of a collection of cars, they are interested in exploring the relationship between a set of variables and MPG (outcome). The are particurlarly interested
in the questions 

- "Is an automatic or manual transmission better for MPG"
- "How different is the MPG between automatic manual transmission?"

## Question
Taket the `mtcars` data set and write up an analysis to answer their question using regression models and exploratory data analyses.

## Form of report
Your report must be
  * Written as a pdf printout of a compiled (using knitr) R markdown document.
    * Do not use any packages that are not in R-base or the library datasets. 
  * Brief. roughly the equivalent of 2 pages long or less. 
  * Include a first paragraph executive summary.
  
### Peer grading
Your report will be graded on the following equally weighted criteria:

1. Did you interpret your coefficients correctly?
2. Did you do some exploratory data analyses?
3. Did you fit multiple models and detail your strategy for model selection?
4. Did you answer the questions of interest or detail why the question(s) is (are) not answerable?
5. Did you do a residual plot and some diagnostics?
6. Did you quantify the uncertainty in your conclusions and/or perform an inference correctly?
7. Did you communicate your findings?
8. Was the report brief (about 2 pages long)?
9. Did it include an executive summary?
10. Was the report done in Rmd (knitr)?

* The grading will be for each of the criteria
  * 1 point - criteria met acceptably 
  * 0 points - criteria not met

Score will be the sum of the points.

