leaflet:
  css: [external/leaflet.css, external/leaflet-rCharts.css, external/legend.css]
  jshead:
    - external/leaflet.js
    - external/leaflet-providers.js
    - external/Control.FullScreen.js
  
  cdn:
    css: http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.css
    jshead: 
      - http://cdn.leafletjs.com/leaflet-0.5.1/leaflet.js
      - https://rawgithub.com/leaflet-extras/leaflet-providers/gh-pages/leaflet-providers.js
      - "http://harrywood.co.uk/maps/examples/leaflet/leaflet-plugins/layer/vector/KML.js"
